version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: stsweng
      MONGO_INITDB_ROOT_PASSWORD: swengproject
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
